# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4\devices\Laser\devTemplate.ui'
#
# Created: Tue Apr 25 16:55:28 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(930, 666)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.powerGroup = QtGui.QGroupBox(Form)
        self.powerGroup.setTitle(_fromUtf8(""))
        self.powerGroup.setObjectName(_fromUtf8("powerGroup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.powerGroup)
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.energyCalcGroup = QtGui.QGroupBox(self.powerGroup)
        self.energyCalcGroup.setObjectName(_fromUtf8("energyCalcGroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.energyCalcGroup)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.currentPowerRadio = QtGui.QRadioButton(self.energyCalcGroup)
        self.currentPowerRadio.setObjectName(_fromUtf8("currentPowerRadio"))
        self.verticalLayout.addWidget(self.currentPowerRadio)
        self.expectedPowerRadio = QtGui.QRadioButton(self.energyCalcGroup)
        self.expectedPowerRadio.setChecked(True)
        self.expectedPowerRadio.setObjectName(_fromUtf8("expectedPowerRadio"))
        self.verticalLayout.addWidget(self.expectedPowerRadio)
        self.gridLayout_4.addWidget(self.energyCalcGroup, 0, 5, 2, 1)
        self.label_4 = QtGui.QLabel(self.powerGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.outputPowerLabel = QtGui.QLabel(self.powerGroup)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputPowerLabel.setFont(font)
        self.outputPowerLabel.setText(_fromUtf8(""))
        self.outputPowerLabel.setObjectName(_fromUtf8("outputPowerLabel"))
        self.gridLayout_4.addWidget(self.outputPowerLabel, 0, 1, 1, 1)
        self.samplePowerLabel = QtGui.QLabel(self.powerGroup)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.samplePowerLabel.setFont(font)
        self.samplePowerLabel.setText(_fromUtf8(""))
        self.samplePowerLabel.setObjectName(_fromUtf8("samplePowerLabel"))
        self.gridLayout_4.addWidget(self.samplePowerLabel, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.powerGroup)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.expectedPowerGroup = QtGui.QGroupBox(self.powerGroup)
        self.expectedPowerGroup.setObjectName(_fromUtf8("expectedPowerGroup"))
        self.gridLayout_9 = QtGui.QGridLayout(self.expectedPowerGroup)
        self.gridLayout_9.setMargin(3)
        self.gridLayout_9.setHorizontalSpacing(1)
        self.gridLayout_9.setVerticalSpacing(3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_5 = QtGui.QLabel(self.expectedPowerGroup)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.expectedPowerSpin = SpinBox(self.expectedPowerGroup)
        self.expectedPowerSpin.setMinimumSize(QtCore.QSize(75, 0))
        self.expectedPowerSpin.setObjectName(_fromUtf8("expectedPowerSpin"))
        self.gridLayout_9.addWidget(self.expectedPowerSpin, 0, 1, 1, 1)
        self.powerAlertCheck = QtGui.QCheckBox(self.expectedPowerGroup)
        self.powerAlertCheck.setChecked(True)
        self.powerAlertCheck.setObjectName(_fromUtf8("powerAlertCheck"))
        self.gridLayout_9.addWidget(self.powerAlertCheck, 1, 0, 1, 1)
        self.toleranceSpin = SpinBox(self.expectedPowerGroup)
        self.toleranceSpin.setMinimumSize(QtCore.QSize(75, 0))
        self.toleranceSpin.setObjectName(_fromUtf8("toleranceSpin"))
        self.gridLayout_9.addWidget(self.toleranceSpin, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.expectedPowerGroup, 0, 2, 2, 1)
        self.gridLayout.addWidget(self.powerGroup, 0, 1, 1, 3)
        self.qSwitchBtn = QtGui.QPushButton(Form)
        self.qSwitchBtn.setCheckable(True)
        self.qSwitchBtn.setObjectName(_fromUtf8("qSwitchBtn"))
        self.gridLayout.addWidget(self.qSwitchBtn, 2, 3, 1, 1)
        self.shutterBtn = QtGui.QPushButton(Form)
        self.shutterBtn.setCheckable(True)
        self.shutterBtn.setObjectName(_fromUtf8("shutterBtn"))
        self.gridLayout.addWidget(self.shutterBtn, 2, 2, 1, 1)
        self.checkPowerBtn = QtGui.QPushButton(Form)
        self.checkPowerBtn.setObjectName(_fromUtf8("checkPowerBtn"))
        self.gridLayout.addWidget(self.checkPowerBtn, 2, 1, 1, 1)
        self.wavelengthGroup = QtGui.QGroupBox(Form)
        self.wavelengthGroup.setTitle(_fromUtf8(""))
        self.wavelengthGroup.setObjectName(_fromUtf8("wavelengthGroup"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wavelengthGroup)
        self.gridLayout_5.setMargin(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.wavelengthGroup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.wavelengthSpin = SpinBox(self.wavelengthGroup)
        self.wavelengthSpin.setSuffix(_fromUtf8(""))
        self.wavelengthSpin.setObjectName(_fromUtf8("wavelengthSpin"))
        self.gridLayout_5.addWidget(self.wavelengthSpin, 0, 1, 1, 1)
        self.wavelengthCombo = QtGui.QComboBox(self.wavelengthGroup)
        self.wavelengthCombo.setObjectName(_fromUtf8("wavelengthCombo"))
        self.wavelengthCombo.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.wavelengthCombo, 0, 2, 1, 1)
        self.GDDEnableCheck = QtGui.QCheckBox(self.wavelengthGroup)
        self.GDDEnableCheck.setObjectName(_fromUtf8("GDDEnableCheck"))
        self.gridLayout_5.addWidget(self.GDDEnableCheck, 1, 0, 1, 1)
        self.GDDSpin = QtGui.QSpinBox(self.wavelengthGroup)
        self.GDDSpin.setMaximum(32000)
        self.GDDSpin.setObjectName(_fromUtf8("GDDSpin"))
        self.gridLayout_5.addWidget(self.GDDSpin, 1, 1, 1, 1)
        self.GDDLimits = QtGui.QLabel(self.wavelengthGroup)
        self.GDDLimits.setObjectName(_fromUtf8("GDDLimits"))
        self.gridLayout_5.addWidget(self.GDDLimits, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.wavelengthGroup, 3, 1, 1, 3)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.transmissionTab = QtGui.QWidget()
        self.transmissionTab.setObjectName(_fromUtf8("transmissionTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.transmissionTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.calibrateBtn = QtGui.QPushButton(self.transmissionTab)
        self.calibrateBtn.setObjectName(_fromUtf8("calibrateBtn"))
        self.gridLayout_10.addWidget(self.calibrateBtn, 1, 0, 1, 1)
        self.deleteBtn = QtGui.QPushButton(self.transmissionTab)
        self.deleteBtn.setObjectName(_fromUtf8("deleteBtn"))
        self.gridLayout_10.addWidget(self.deleteBtn, 1, 1, 1, 1)
        self.calibrationList = QtGui.QTreeWidget(self.transmissionTab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.calibrationList.setFont(font)
        self.calibrationList.setRootIsDecorated(False)
        self.calibrationList.setItemsExpandable(False)
        self.calibrationList.setObjectName(_fromUtf8("calibrationList"))
        self.calibrationList.header().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.calibrationList, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.transmissionTab)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.scanLabel = QtGui.QLabel(self.groupBox)
        self.scanLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scanLabel.setObjectName(_fromUtf8("scanLabel"))
        self.gridLayout_2.addWidget(self.scanLabel, 3, 2, 1, 1)
        self.meterCombo = InterfaceCombo(self.groupBox)
        self.meterCombo.setObjectName(_fromUtf8("meterCombo"))
        self.gridLayout_2.addWidget(self.meterCombo, 3, 1, 1, 1)
        self.measurementSpin = SpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measurementSpin.sizePolicy().hasHeightForWidth())
        self.measurementSpin.setSizePolicy(sizePolicy)
        self.measurementSpin.setMinimum(0.0)
        self.measurementSpin.setMaximum(100.0)
        self.measurementSpin.setProperty("value", 1.0)
        self.measurementSpin.setObjectName(_fromUtf8("measurementSpin"))
        self.gridLayout_2.addWidget(self.measurementSpin, 3, 4, 1, 1)
        self.channelCombo = QtGui.QComboBox(self.groupBox)
        self.channelCombo.setObjectName(_fromUtf8("channelCombo"))
        self.gridLayout_2.addWidget(self.channelCombo, 4, 1, 1, 1)
        self.settlingSpin = SpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settlingSpin.sizePolicy().hasHeightForWidth())
        self.settlingSpin.setSizePolicy(sizePolicy)
        self.settlingSpin.setObjectName(_fromUtf8("settlingSpin"))
        self.gridLayout_2.addWidget(self.settlingSpin, 4, 4, 1, 1)
        self.powerToUseLabel = QtGui.QLabel(self.groupBox)
        self.powerToUseLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.powerToUseLabel.setObjectName(_fromUtf8("powerToUseLabel"))
        self.gridLayout_2.addWidget(self.powerToUseLabel, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.powerIndicatorLabel = QtGui.QLabel(self.groupBox)
        self.powerIndicatorLabel.setText(_fromUtf8(""))
        self.powerIndicatorLabel.setObjectName(_fromUtf8("powerIndicatorLabel"))
        self.gridLayout_2.addWidget(self.powerIndicatorLabel, 2, 1, 1, 1)
        self.powerToUseSpin = SpinBox(self.groupBox)
        self.powerToUseSpin.setObjectName(_fromUtf8("powerToUseSpin"))
        self.gridLayout_2.addWidget(self.powerToUseSpin, 2, 4, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 2, 0, 1, 2)
        self.tabWidget.addTab(self.transmissionTab, _fromUtf8(""))
        self.powerModTab = QtGui.QWidget()
        self.powerModTab.setObjectName(_fromUtf8("powerModTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.powerModTab)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.powerCalibrationTree = QtGui.QTreeWidget(self.powerModTab)
        self.powerCalibrationTree.setObjectName(_fromUtf8("powerCalibrationTree"))
        self.gridLayout_3.addWidget(self.powerCalibrationTree, 0, 0, 1, 1)
        self.powerPlot = PlotWidget(self.powerModTab)
        self.powerPlot.setObjectName(_fromUtf8("powerPlot"))
        self.gridLayout_3.addWidget(self.powerPlot, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.calibratePowerBtn = QtGui.QPushButton(self.powerModTab)
        self.calibratePowerBtn.setObjectName(_fromUtf8("calibratePowerBtn"))
        self.horizontalLayout.addWidget(self.calibratePowerBtn)
        self.label_6 = QtGui.QLabel(self.powerModTab)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.fitFunctionCombo = ComboBox(self.powerModTab)
        self.fitFunctionCombo.setObjectName(_fromUtf8("fitFunctionCombo"))
        self.horizontalLayout.addWidget(self.fitFunctionCombo)
        self.recalculateFitBtn = QtGui.QPushButton(self.powerModTab)
        self.recalculateFitBtn.setObjectName(_fromUtf8("recalculateFitBtn"))
        self.horizontalLayout.addWidget(self.recalculateFitBtn)
        self.deletePowerBtn = QtGui.QPushButton(self.powerModTab)
        self.deletePowerBtn.setObjectName(_fromUtf8("deletePowerBtn"))
        self.horizontalLayout.addWidget(self.deletePowerBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.powerModGroup = QtGui.QGroupBox(self.powerModTab)
        self.powerModGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.powerModGroup.setObjectName(_fromUtf8("powerModGroup"))
        self.gridLayout_8 = QtGui.QGridLayout(self.powerModGroup)
        self.gridLayout_8.setMargin(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_9 = QtGui.QLabel(self.powerModGroup)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.minVSpin = SpinBox(self.powerModGroup)
        self.minVSpin.setMinimum(-99.0)
        self.minVSpin.setSingleStep(0.01)
        self.minVSpin.setProperty("value", -0.2)
        self.minVSpin.setObjectName(_fromUtf8("minVSpin"))
        self.gridLayout_7.addWidget(self.minVSpin, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.powerModGroup)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 2, 1, 1)
        self.stepsSpin = SpinBox(self.powerModGroup)
        self.stepsSpin.setMinimum(10.0)
        self.stepsSpin.setMaximum(1000.0)
        self.stepsSpin.setProperty("value", 20.0)
        self.stepsSpin.setObjectName(_fromUtf8("stepsSpin"))
        self.gridLayout_7.addWidget(self.stepsSpin, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.powerModGroup)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        self.maxVSpin = SpinBox(self.powerModGroup)
        self.maxVSpin.setSingleStep(0.01)
        self.maxVSpin.setProperty("value", 1.2)
        self.maxVSpin.setObjectName(_fromUtf8("maxVSpin"))
        self.gridLayout_7.addWidget(self.maxVSpin, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.powerModGroup, 2, 0, 1, 2)
        self.tabWidget.addTab(self.powerModTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 4, 1, 1, 3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.energyCalcGroup.setTitle(_translate("Form", "For energy calculations use:", None))
        self.currentPowerRadio.setText(_translate("Form", "Current Power", None))
        self.expectedPowerRadio.setText(_translate("Form", "Expected Power", None))
        self.label_4.setText(_translate("Form", "Current Output Power:", None))
        self.label_8.setText(_translate("Form", "Power at sample (calc.):", None))
        self.expectedPowerGroup.setTitle(_translate("Form", "Expected Power:", None))
        self.label_5.setText(_translate("Form", "Expected Output Power:", None))
        self.powerAlertCheck.setText(_translate("Form", "Alert me to power changes larger than:", None))
        self.qSwitchBtn.setText(_translate("Form", "Turn On QSwitch", None))
        self.shutterBtn.setText(_translate("Form", "Open Shutter", None))
        self.checkPowerBtn.setText(_translate("Form", "Check Power", None))
        self.label_7.setText(_translate("Form", "Current Wavelength: ", None))
        self.wavelengthCombo.setItemText(0, _translate("Form", "Set wavelength for:", None))
        self.GDDEnableCheck.setText(_translate("Form", "GDD Enable", None))
        self.GDDLimits.setText(_translate("Form", "GDD Limits", None))
        self.calibrateBtn.setText(_translate("Form", "Calibrate Transmission", None))
        self.deleteBtn.setText(_translate("Form", "Delete", None))
        self.calibrationList.headerItem().setText(0, _translate("Form", "Optics", None))
        self.calibrationList.headerItem().setText(1, _translate("Form", "Wavelength", None))
        self.calibrationList.headerItem().setText(2, _translate("Form", "Transmission", None))
        self.calibrationList.headerItem().setText(3, _translate("Form", "Power at Sample", None))
        self.calibrationList.headerItem().setText(4, _translate("Form", "Date", None))
        self.groupBox.setTitle(_translate("Form", "Transmission Calibration Parameters", None))
        self.label_12.setText(_translate("Form", "Channel:", None))
        self.label.setText(_translate("Form", "Settling Duration:", None))
        self.label_3.setText(_translate("Form", "Power Meter:", None))
        self.scanLabel.setText(_translate("Form", "Measurement Duration", None))
        self.measurementSpin.setSuffix(_translate("Form", " s", None))
        self.settlingSpin.setToolTip(_translate("Form", "Specify the time it takes for the selected power meter to settle on a value.", None))
        self.powerToUseLabel.setText(_translate("Form", "Power to Use:", None))
        self.label_2.setText(_translate("Form", "Power Indicator:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.transmissionTab), _translate("Form", "Transmission Calibration", None))
        self.powerCalibrationTree.headerItem().setText(0, _translate("Form", "Wavelength", None))
        self.powerCalibrationTree.headerItem().setText(1, _translate("Form", "Date", None))
        self.powerCalibrationTree.headerItem().setText(2, _translate("Form", "Fit function", None))
        self.powerCalibrationTree.headerItem().setText(3, _translate("Form", "Fit parameters", None))
        self.powerCalibrationTree.headerItem().setText(4, _translate("Form", "Fit error", None))
        self.calibratePowerBtn.setText(_translate("Form", "Run Power Calibration", None))
        self.label_6.setText(_translate("Form", "Fit Function:", None))
        self.recalculateFitBtn.setText(_translate("Form", "Recalculate Fit", None))
        self.deletePowerBtn.setText(_translate("Form", "Delete", None))
        self.powerModGroup.setTitle(_translate("Form", "Power Modulation Parameters", None))
        self.label_9.setText(_translate("Form", "Minimum Voltage:", None))
        self.minVSpin.setSuffix(_translate("Form", "V", None))
        self.label_11.setText(_translate("Form", "Number of Steps: ", None))
        self.label_10.setText(_translate("Form", "Maximum Voltage:", None))
        self.maxVSpin.setSuffix(_translate("Form", "V", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.powerModTab), _translate("Form", "Power Modulation Calibration", None))

from acq4.pyqtgraph import ComboBox, PlotWidget, SpinBox
from acq4.util.InterfaceCombo import InterfaceCombo
